FROM python:3.6.7
RUN apt-get update
RUN apt-get install libev-dev -y
RUN apt-get install ffmpeg -y
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip3 install gunicorn[gevent]
ADD . /verifier
WORKDIR /verifier