FROM livepeer/verifier:latest
RUN pip3 install gunicorn[gevent]
ADD . /verifier
WORKDIR /verifier
ENV ENV=Prod
ENV API_HOST=0.0.0.0
ENV API_PORT=5000
ENV VERIFICATION_MODEL_URI=http://storage.googleapis.com/verification-models/verification-metamodel-2020-07-06.tar.xz
CMD gunicorn --worker-class gevent --workers 8 --bind $API_HOST:$API_PORT api.api:APP --max-requests 10000 --timeout 30 --keep-alive 2 --log-level info
